name: 'Terraform Infrastructure Setup'

on:
  push:
    branches:
    - main
    paths: 
    - infra/**
  pull_request:
    branches:
    - main
    paths: 
    - infra/**

jobs: 
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    environment: staging 
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.2
        terraform_wrapper: false
    - name: Terraform Init
      id: init
      run: terraform init
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      working-directory: ./infra