name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Destroy'
        type: choice
        options:
        - Terraform_destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  Terraform_Destroy:
    name: Terraform Destroy
    if: ${{ github.event.inputs.action == 'Terraform_destroy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2
          terraform_wrapper: false

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set EKS Kubeconfig 
        run: "aws eks update-kubeconfig --region us-east-1 --name golang-api-demo"
      
      # Delete the helm releases to cleanup AWS LBs
      - name: Delete Helm releases
        run: |
          if ! helm ls --all --short | xargs -L1 helm delete; then
            echo "Golang API is already destroyed"
          fi

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: infra
        shell: bash

      - name: Terraform Destroy
        id: destroy
        working-directory: infra
        shell: bash
        run: terraform destroy -auto-approve